---
- hosts: web
  tasks:
  - name: remove service
    command: docker service rm devops-service
    ignore_errors: yes

  - name: remove current docker image
    command: docker image rm -f sregor/devops-image:latest
    ignore_errors: yes
  
  - name: pull image docker hub 
    command: docker pull sregor/devops-image:latest 
  
  - name: creating service
    command: docker service create --name devops-service  --replicas 3 -p 8080:8080 sregor/devops-image:latest
